MASTER_HOST = "50.23.83.242"
SLAVE_HOST = "50.23.83.248"
HBASE_PORT = 9090
SPARK_PORT = 7077
HDFS_PORT = 8020
WEB_APP_PORT = 5000

LYRICS_TO_ARTISTS_TABLE = 'lyrics_to_artists'
ARTISTS_WORDS_COUNT_TABLE = 'artists_to_words_count'
ARTISTS_WORDS_TFIDF_TABLE = 'artists_to_words_tfidf'
WORDS_COUNT_TABLE = 'words_count'
TWO_GRAMS_COUNT_TABLE = 'two_grams_count'
THREE_GRAMS_COUNT_TABLE = 'three_grams_count'
